/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import controladores.MascotaDAO;
import controladores.VeterinarioDAO;
import modelos.MascotaDTO;
import modelos.VeterinarioDTO;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author hzdat
 */
public class DialogAsignarVeterinario extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAsignarVeterinario.class.getName());

    /**
     * Creates new form DialogAsignarVeterinario
     */
    public DialogAsignarVeterinario(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        initComponents();

        setLocationRelativeTo(null);

        cargarMascotas();
        cargarVeterinarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        comboMascotas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboVeterinarios = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboMascotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ASIGNAR MASCOTA A VETERINARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID MASCOTA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("ID VETERINARIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        comboVeterinarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboVeterinarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btnAsignar.setText("ASIGNAR");
        btnAsignar.addActionListener(this::btnAsignarActionPerformed);
        jPanel1.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        try {

            // coger String del combo
            String idMascotaStr = (String) comboMascotas.getSelectedItem();
            String idVetStr = (String) comboVeterinarios.getSelectedItem();

            if (idMascotaStr == null || idVetStr == null) {
                JOptionPane.showMessageDialog(this, "Selecciona datos");
                return;
            }

            // convertir a int
            int idMascota = Integer.parseInt(idMascotaStr);
            int idVeterinario = Integer.parseInt(idVetStr);

            MascotaDAO dao = new MascotaDAO();

            // buscar mascota
            MascotaDTO mascota = dao.findByPk(idMascota);

            if (mascota == null) {
                JOptionPane.showMessageDialog(this, "Mascota no existe");
                return;
            }

            // asignar veterinario
            mascota.setId_veterinario(idVeterinario);

            // actualizar
            dao.updateMascota(idMascota, mascota);

            JOptionPane.showMessageDialog(this, "Asignado correctamente");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error");

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAsignarVeterinario dialog = new DialogAsignarVeterinario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargarMascotas() {

        try {

            MascotaDAO dao = new MascotaDAO();
            // lista de mascotas
            List<MascotaDTO> lista = dao.getAll();

            // vaciar el combobox antes de meter cosas , flow nextline()
            comboMascotas.removeAllItems();

            for (MascotaDTO m : lista) {
                // convertir id a String
                comboMascotas.addItem(String.valueOf(m.getId_mascota()));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void cargarVeterinarios() {

        try {

            VeterinarioDAO dao = new VeterinarioDAO();
            // lista de veterinarios
            List<VeterinarioDTO> lista = dao.getAll();

            comboVeterinarios.removeAllItems();

            for (VeterinarioDTO v : lista) {
                // convertir id a String
                comboVeterinarios.addItem(String.valueOf(v.getId_veterinario()));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> comboMascotas;
    private javax.swing.JComboBox<String> comboVeterinarios;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
