/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class DialogVeterinarios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogVeterinarios.class.getName());

    /**
     * Creates new form DialogVeterinarios
     */
    public DialogVeterinarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // centrar ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnMostrarVeterinarios1 = new javax.swing.JButton();
        btnBuscarVeterinario = new javax.swing.JButton();
        btnInsertarVeterinario = new javax.swing.JButton();
        btnModificarVeterinario = new javax.swing.JButton();
        btnBorrarVeterinario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        btnMostrarVeterinarios1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnMostrarVeterinarios1.setText("MOSTRAR VETERINARIOS");
        btnMostrarVeterinarios1.addActionListener(this::btnMostrarVeterinarios1ActionPerformed);
        jPanel1.add(btnMostrarVeterinarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, -1));

        btnBuscarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBuscarVeterinario.setText("BUSCAR UN VETERINARIO");
        btnBuscarVeterinario.addActionListener(this::btnBuscarVeterinarioActionPerformed);
        jPanel1.add(btnBuscarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, -1));

        btnInsertarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnInsertarVeterinario.setText("INSERTAR VETERINARIO");
        btnInsertarVeterinario.addActionListener(this::btnInsertarVeterinarioActionPerformed);
        jPanel1.add(btnInsertarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 230, -1));

        btnModificarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnModificarVeterinario.setText("MODIFICAR VETERINARIO");
        btnModificarVeterinario.addActionListener(this::btnModificarVeterinarioActionPerformed);
        jPanel1.add(btnModificarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 230, -1));

        btnBorrarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBorrarVeterinario.setText("BORRAR VETERINARIO");
        btnBorrarVeterinario.addActionListener(this::btnBorrarVeterinarioActionPerformed);
        jPanel1.add(btnBorrarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinario_def-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 370, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVeterinarioActionPerformed
        // TODO add your handling code here:
        try {

            String input = JOptionPane.showInputDialog(
                    this,
                    "Introduce ID del veterinario"
            );

            if (input == null) {
                return;
            }

            int id = Integer.parseInt(input);

            controladores.VeterinarioDAO dao = new controladores.VeterinarioDAO();

            modelos.VeterinarioDTO vet = dao.findByPk(id);

            if (vet == null) {

                // 👇 ahora sí estilo clase
                JOptionPane.showMessageDialog(this,
                        "Veterinario no encontrado");

            } else {

                JOptionPane.showMessageDialog(this,
                        "ID: " + vet.getId_veterinario()
                        + " - NIF: " + vet.getNif()
                        + " - Nombre: " + vet.getNomvete()
                        + " - Dirección: " + vet.getDir()
                        + " - Teléfono: " + vet.getTelefono()
                        + " - Email: " + vet.getEmail());
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID debe ser numérico");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error al buscar");

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarVeterinarioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        // esto cierra solo el JDialog, así vuelvo a la ventana principal
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnMostrarVeterinarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVeterinarios1ActionPerformed
        // TODO add your handling code here:
        // Crear diálogo de mostrar veterinarios
        DialogMostrarVeterinarios dialogo
                = new DialogMostrarVeterinarios(null, true);

        // Mostrar diálogo
        dialogo.setVisible(true);
    }//GEN-LAST:event_btnMostrarVeterinarios1ActionPerformed

    private void btnInsertarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarVeterinarioActionPerformed
        // TODO add your handling code here:
        DialogInsertarVeterinario dialogo
                = new DialogInsertarVeterinario(null, true);

        dialogo.setVisible(true);
    }//GEN-LAST:event_btnInsertarVeterinarioActionPerformed

    private void btnBorrarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVeterinarioActionPerformed
        // TODO add your handling code here:
        try {

            // =========================================
            // PEDIR ID
            // =========================================
            String id = JOptionPane.showInputDialog(
                    this,
                    "Introduce ID del veterinario a borrar"
            );

            // Si cancela
            if (id == null) {
                return;
            }

            // Convertir a entero
            int id_vet = Integer.parseInt(id);

            // DAO
            controladores.VeterinarioDAO dao = new controladores.VeterinarioDAO();

            // BUSCAR VETERINARIO
            modelos.VeterinarioDTO vet = dao.findByPk(id_vet);

            // Si no existe
            if (vet == null) {

                JOptionPane.showMessageDialog(this,
                        "Veterinario no encontrado");

                return;
            }

            // CONFIRMAR BORRADO
            // joptionpane , tiene metodos de si y no
            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que quieres borrar el veterinario?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            // Si dice NO → salir
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            // BORRAR
            dao.deleteVeterinario(vet);
            JOptionPane.showMessageDialog(this,
                    "Veterinario borrado correctamente");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID debe ser numérico");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error al borrar");

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBorrarVeterinarioActionPerformed

    private void btnModificarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVeterinarioActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this,
                "Introduce ID del veterinario");

        if (input == null) {
            return;
        }

        int id = Integer.parseInt(input);

        DialogModificarVeterinario dialogo
                = new DialogModificarVeterinario(null, true, id);

        dialogo.setVisible(true);
    }//GEN-LAST:event_btnModificarVeterinarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarVeterinario;
    private javax.swing.JButton btnBuscarVeterinario;
    private javax.swing.JButton btnInsertarVeterinario;
    private javax.swing.JButton btnModificarVeterinario;
    private javax.swing.JButton btnMostrarVeterinarios1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
