/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import controladores.VeterinarioDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelos.VeterinarioDTO;

/**
 *
 * @author hzdat
 */
public class DialogMostrarVeterinarios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogMostrarVeterinarios.class.getName());

    /**
     * Creates new form DialogMostrarVeterinarios
     */
    public DialogMostrarVeterinarios(java.awt.Frame parent, boolean modal) {

        // Constructor del padre del hijo y del espiritu santo
        super(parent, modal);

        // Inicializar componentes
        initComponents();

        // Centrar ventana
        setLocationRelativeTo(null);

        // Cargar datos en JTable
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVeterinarios = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tablaVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVeterinarios);

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        // Cerrar diálogo
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // MÉTODO PARA CARGAR LOS DATOS EN LA TABLA
    private void cargarTabla() {

        try {

            // Crear objeto DAO
            VeterinarioDAO dao = new VeterinarioDAO();

            // Obtener lista de veterinarios desde la BD
            List<VeterinarioDTO> lista = dao.getAll();

            // Crear modelo para la JTable
            DefaultTableModel modelo = new DefaultTableModel();

            // Añadir nombres de columnas
            modelo.addColumn("ID");
            modelo.addColumn("NIF");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("DIRECCIÓN");
            modelo.addColumn("TELÉFONO");
            modelo.addColumn("EMAIL");

            // Recorrer lista de veterinarios
            for (VeterinarioDTO v : lista) {

                // Crear array con datos de una fila
                Object[] fila = {
                    v.getId_veterinario(),
                    v.getNif(),
                    v.getNomvete(),
                    v.getDir(),
                    v.getTelefono(),
                    v.getEmail()
                };

                // Añadir fila al modelo
                modelo.addRow(fila);
            }

            // Asignar modelo a la tabla
            tablaVeterinarios.setModel(modelo);

        } catch (SQLException e) {

            // Mostrar error por consola
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVeterinarios;
    // End of variables declaration//GEN-END:variables
}
