/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author usuario
 */
public class DialogMascotas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogMascotas.class.getName());

    /**
     * Creates new form DialogMascotas
     */
    public DialogMascotas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         // centrar ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMostrarMascotas = new javax.swing.JButton();
        btnBuscarUnaMascota = new javax.swing.JButton();
        btnInsertarMascota = new javax.swing.JButton();
        btnModificarMascota = new javax.swing.JButton();
        btnBorrarMascota = new javax.swing.JButton();
        btnMascotasDeUnVet = new javax.swing.JButton();
        btnAsignarVeterinario = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarMascotas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnMostrarMascotas.setText("MOSTRAR MASCOTAS");
        btnMostrarMascotas.addActionListener(this::btnMostrarMascotasActionPerformed);
        jPanel1.add(btnMostrarMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 50));

        btnBuscarUnaMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBuscarUnaMascota.setText("BUSCAR UNA MASCOTA");
        jPanel1.add(btnBuscarUnaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, 50));

        btnInsertarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnInsertarMascota.setText("INSERTAR MASCOTA");
        btnInsertarMascota.addActionListener(this::btnInsertarMascotaActionPerformed);
        jPanel1.add(btnInsertarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 50));

        btnModificarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnModificarMascota.setText("MODIFICAR MASCOTA");
        jPanel1.add(btnModificarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, 50));

        btnBorrarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBorrarMascota.setText("BORRAR MASCOTA");
        jPanel1.add(btnBorrarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 210, 60));

        btnMascotasDeUnVet.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnMascotasDeUnVet.setText("MASCOTAS DE UN VETERINARIO");
        jPanel1.add(btnMascotasDeUnVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 280, 60));

        btnAsignarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAsignarVeterinario.setText("ASIGNAR VETERINARIO");
        jPanel1.add(btnAsignarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 230, 60));

        btnVolver.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mascotas_definitiva.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 240, 700, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMascotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarMascotasActionPerformed

    private void btnInsertarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarMascotaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         this.dispose();
        // esto cierra solo el JDialog, así vuelvo a la ventana principal
    }//GEN-LAST:event_btnVolverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarVeterinario;
    private javax.swing.JButton btnBorrarMascota;
    private javax.swing.JButton btnBuscarUnaMascota;
    private javax.swing.JButton btnInsertarMascota;
    private javax.swing.JButton btnMascotasDeUnVet;
    private javax.swing.JButton btnModificarMascota;
    private javax.swing.JButton btnMostrarMascotas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
