/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import controladores.VeterinarioDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelos.VeterinarioDTO;

/**
 *
 * @author hzdat
 */
public class DialogModificarVeterinario extends javax.swing.JDialog {

    private int idVeterinario;

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(DialogModificarVeterinario.class.getName());

    /**
     * Creates new form DialogModificarVeterinario
     */
    public DialogModificarVeterinario(java.awt.Frame parent, boolean modal, int idVterinario) {

        super(parent, modal);

        initComponents();

        setLocationRelativeTo(null);

        this.idVeterinario = idVterinario;

        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        e = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        b = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        c = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        d = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        e.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        e.setForeground(new java.awt.Color(51, 51, 51));
        e.setText("Teléfono");

        f.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f.setForeground(new java.awt.Color(51, 51, 51));
        f.setText("Email");

        a.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        a.setForeground(new java.awt.Color(51, 51, 51));
        a.setText("ID");

        b.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b.setForeground(new java.awt.Color(51, 51, 51));
        b.setText("NIF");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c.setForeground(new java.awt.Color(51, 51, 51));
        c.setText("Nombre");

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        d.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d.setForeground(new java.awt.Color(51, 51, 51));
        d.setText("Dirección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnCerrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnGuardar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(d)
                                                                                        .addGap(89, 89, 89))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(e)
                                                                                .addGap(93, 93, 93)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(f)
                                                                .addGap(116, 116, 116)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtEmail)
                                                        .addComponent(txtTelefono)
                                                        .addComponent(txtDireccion,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(a)
                                                                                        .addGap(138, 138, 138))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(b)
                                                                                .addGap(130, 130, 130)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(c)
                                                                .addGap(96, 96, 96)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtNombre)
                                                        .addComponent(txtNif)
                                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(47, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(a)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b)
                                        .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(c)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(d)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(e)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(f)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnGuardar)
                                        .addComponent(btnCerrar))
                                .addGap(24, 24, 24)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            String nif = txtNif.getText();
            String nombre = txtNombre.getText().isEmpty() ? null : txtEmail.getText();
            String direccion = txtDireccion.getText().isEmpty() ? null : txtEmail.getText();         
            String telefono = txtTelefono.getText().isEmpty() ? null : txtTelefono.getText();
            String email = txtEmail.getText().isEmpty() ? null : txtEmail.getText();

            if (nif.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El NIF es obligatorio");
            } else {
                VeterinarioDTO nuevo = new VeterinarioDTO(
                        idVeterinario, nif, nombre, direccion, telefono, email);

                VeterinarioDAO dao = new VeterinarioDAO();

                dao.updateVeterinario(idVeterinario, nuevo);

                JOptionPane.showMessageDialog(this, "Modificado correctamente");
                // goes back
                this.dispose();

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error al modificar");
            e.printStackTrace();
        }

    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnCerrarActionPerformed

    private void cargarDatos() {

        try {

            // crear el DAO para acceder a la base de datos
            VeterinarioDAO dao = new VeterinarioDAO();

            // buscar el veterinario por su ID (que ya guardamos antes)
            VeterinarioDTO vet = dao.findByPk(idVeterinario);

            // comprobar que el veterinario existe
            if (vet != null) {

                // poner el ID en el campo de texto
                txtId.setText(String.valueOf(vet.getId_veterinario()));
                // hacer que el ID no se pueda modificar
                txtId.setEditable(false);
                // poner el nif en el campo
                txtNif.setText(vet.getNif());
                // poner el nombre
                txtNombre.setText(vet.getNomvete());
                // poner la dirección
                txtDireccion.setText(vet.getDir());
                // poner el teléfono
                txtTelefono.setText(vet.getTelefono());
                // poner el email
                txtEmail.setText(vet.getEmail());
            }

        } catch (SQLException e) {

            // mostrar mensaje si hay error con la base de datos
            JOptionPane.showMessageDialog(this, "Error al cargar datos");

            // imprimir error en consola (para depurar)
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
