/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;

import modelos.MascotaDTO;

/**
 *
 * @author usuario
 */
public class DialogMascotas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(DialogMascotas.class.getName());

    /**
     * Creates new form DialogMascotas
     */
    public DialogMascotas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // centrar ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMostrarMascotas = new javax.swing.JButton();
        btnBuscarUnaMascota = new javax.swing.JButton();
        btnInsertarMascota = new javax.swing.JButton();
        btnModificarMascota = new javax.swing.JButton();
        btnBorrarMascota = new javax.swing.JButton();
        btnMascotasDeUnVet = new javax.swing.JButton();
        btnAsignarVeterinario = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarMascotas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnMostrarMascotas.setText("MOSTRAR MASCOTAS");
        btnMostrarMascotas.addActionListener(this::btnMostrarMascotasActionPerformed);
        jPanel1.add(btnMostrarMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 50));

        btnBuscarUnaMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBuscarUnaMascota.setText("BUSCAR UNA MASCOTA");
        btnBuscarUnaMascota.addActionListener(this::btnBuscarUnaMascotaActionPerformed);
        jPanel1.add(btnBuscarUnaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, 50));

        btnInsertarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnInsertarMascota.setText("INSERTAR MASCOTA");
        btnInsertarMascota.addActionListener(this::btnInsertarMascotaActionPerformed);
        jPanel1.add(btnInsertarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 50));

        btnModificarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnModificarMascota.setText("MODIFICAR MASCOTA");
        btnModificarMascota.addActionListener(this::btnModificarMascotaActionPerformed);
        jPanel1.add(btnModificarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, 50));

        btnBorrarMascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBorrarMascota.setText("BORRAR MASCOTA");
        btnBorrarMascota.addActionListener(this::btnBorrarMascotaActionPerformed);
        jPanel1.add(btnBorrarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 210, 60));

        btnMascotasDeUnVet.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnMascotasDeUnVet.setText("MASCOTAS DE UN VETERINARIO");
        btnMascotasDeUnVet.addActionListener(this::btnMascotasDeUnVetActionPerformed);
        jPanel1.add(btnMascotasDeUnVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 280, 60));

        btnAsignarVeterinario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAsignarVeterinario.setText("ASIGNAR VETERINARIO");
        btnAsignarVeterinario.addActionListener(this::btnAsignarVeterinarioActionPerformed);
        jPanel1.add(btnAsignarVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 230, 60));

        btnVolver.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mascotas_definitiva.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 240, 700, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarMascotasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMostrarMascotasActionPerformed
        // TODO add your handling code here:
        DialogMostrarMascotas dialogo = new DialogMostrarMascotas(null, true);

        dialogo.setVisible(true);
    }// GEN-LAST:event_btnMostrarMascotasActionPerformed

    private void btnInsertarMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertarMascotaActionPerformed
        // TODO add your handling code here:
        DialogInsertarMascota dialogo = new DialogInsertarMascota(null, true);

        dialogo.setVisible(true);
    }// GEN-LAST:event_btnInsertarMascotaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        // esto cierra solo el JDialog, así vuelvo a la ventana principal
    }// GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarUnaMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarUnaMascotaActionPerformed
        // TODO add your handling code here:

        try {

            // pedir id
            String id = JOptionPane.showInputDialog(this,
                    "Introduce ID de la mascota");

            if (id == null) {
                System.out.println("NULL");
            } else {
                // pasamos string a int
                int id_mascota = Integer.parseInt(id);

                // dao
                controladores.MascotaDAO dao = new controladores.MascotaDAO();

                // buscamos la fokin mascota
                MascotaDTO mascota = dao.findByPk(id_mascota);

                if (mascota == null) {

                    JOptionPane.showMessageDialog(this,
                            "Mascota no encontrada");

                } else {

                    JOptionPane.showMessageDialog(this,
                            "ID: " + mascota.getId_mascota()
                                    + "\nChip: " + mascota.getNumchip()
                                    + "\nNombre: " + mascota.getNommasc()
                                    + "\nPeso: " + mascota.getPeso()
                                    + "\nFecha: " + mascota.getFecnacim()
                                    + "\nTipo: " + mascota.getTipo()
                                    + "\nID Veterinario: " + mascota.getId_veterinario());
                }

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID debe ser numérico");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error al buscar");

            e.printStackTrace();
        }

    }// GEN-LAST:event_btnBuscarUnaMascotaActionPerformed

    private void btnBorrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBorrarMascotaActionPerformed
        // TODO add your handling code here:

        try {

            // pedir id
            String id = JOptionPane.showInputDialog(this,
                    "Introduce ID de la mascota a borrar");

            if (id == null) {
                return;
            }

            int id_mascota = Integer.parseInt(id);

            // dao
            controladores.MascotaDAO dao = new controladores.MascotaDAO();

            // buscar
            MascotaDTO mascota = dao.findByPk(id_mascota);

            if (mascota == null) {

                JOptionPane.showMessageDialog(this,
                        "Mascota no encontrada");
                return;
            }

            // confirmar
            // JOPtion pane tiene metodos de ventana emergente con opcion si y no ,
            // guapisimo
            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que quieres borrar la mascota?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION); // aqui muestro la opcion si/no

            if (opcion == JOptionPane.YES_OPTION) {
                // borrar
                dao.deleteMascota(mascota);

                JOptionPane.showMessageDialog(this,
                        "Mascota borrada correctamente");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID debe ser numérico");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error al borrar");

            e.printStackTrace();
        }

    }// GEN-LAST:event_btnBorrarMascotaActionPerformed

    private void btnMascotasDeUnVetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMascotasDeUnVetActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog(this,
                "Introduce ID del veterinario");

        if (id == null) {
            System.out.println("id = null");
        } else {

            int idVet = Integer.parseInt(id);

            DialogMascotasDeVeterinario dialogo = new DialogMascotasDeVeterinario(null, true, idVet);

            dialogo.setVisible(true);

        }

    }// GEN-LAST:event_btnMascotasDeUnVetActionPerformed

    private void btnAsignarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAsignarVeterinarioActionPerformed
        // TODO add your handling code here:
        // crear diálogo
        DialogAsignarVeterinario dialogo = new DialogAsignarVeterinario(null, true);

        // mostrarlo
        dialogo.setVisible(true);
    }// GEN-LAST:event_btnAsignarVeterinarioActionPerformed

    private void btnModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarMascotaActionPerformed
        // TODO add your handling code here:

        String id = JOptionPane.showInputDialog(this,
                "Introduce ID de la mascota");

        if (id == null) {
            System.out.println("id = null");
        } else {
            int id_mascota = Integer.parseInt(id);

            DialogModificarMascota dialogo = new DialogModificarMascota(null, true, id_mascota);

            dialogo.setVisible(true);

        }

    }// GEN-LAST:event_btnModificarMascotaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarVeterinario;
    private javax.swing.JButton btnBorrarMascota;
    private javax.swing.JButton btnBuscarUnaMascota;
    private javax.swing.JButton btnInsertarMascota;
    private javax.swing.JButton btnMascotasDeUnVet;
    private javax.swing.JButton btnModificarMascota;
    private javax.swing.JButton btnMostrarMascotas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
