/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
         // centrar ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionMascotas = new javax.swing.JButton();
        btnGestionVeterinarios1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Bienvenido a la app  -> GESTIONVETERINARIA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 30, 403, 64);

        btnGestionMascotas.setBackground(new java.awt.Color(0, 102, 102));
        btnGestionMascotas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnGestionMascotas.setText("GestionMascotas");
        btnGestionMascotas.addActionListener(this::btnGestionMascotasActionPerformed);
        jPanel1.add(btnGestionMascotas);
        btnGestionMascotas.setBounds(510, 150, 200, 60);

        btnGestionVeterinarios1.setBackground(new java.awt.Color(0, 102, 102));
        btnGestionVeterinarios1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnGestionVeterinarios1.setText("GestionVeterinarios");
        btnGestionVeterinarios1.addActionListener(this::btnGestionVeterinarios1ActionPerformed);
        jPanel1.add(btnGestionVeterinarios1);
        btnGestionVeterinarios1.setBounds(510, 260, 200, 60);

        btnSalir.setBackground(new java.awt.Color(102, 102, 0));
        btnSalir.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir);
        btnSalir.setBounds(100, 180, 87, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinario.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 840, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMascotasActionPerformed
        // TODO add your handling code here:

        DialogMascotas gestionMascotas = new DialogMascotas(this, true);
        // El boolean modal es true 
        // para que no puedas toc
        // para que se vea la ventana del JDialogar la ventana principal hasta cerrar el diálogo
        gestionMascotas.setVisible(true);
        // para que se vea la ventana del JDialog
    }//GEN-LAST:event_btnGestionMascotasActionPerformed

    private void btnGestionVeterinarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVeterinarios1ActionPerformed
        // TODO add your handling code here:
        
         DialogVeterinarios gestionVeterinarios = new DialogVeterinarios(this, true);
        // El boolean modal es true 
        // para que no puedas toc
        // para que se vea la ventana del JDialogar la ventana principal hasta cerrar el diálogo
        gestionVeterinarios.setVisible(true);
        // para que se vea la ventana del JDialog
    }//GEN-LAST:event_btnGestionVeterinarios1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        // esto sirve para cerrar programa
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionMascotas;
    private javax.swing.JButton btnGestionVeterinarios1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
